---
- name: Remove k8s repo
  yum_repository:
    name: Kubernetes
    state: absent
  notify: yum-clean-metadata

- name: Add kubernetes repo
  yum_repository:
    name: Kubernetes
    description: k8s repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: no

- name: yum-update-cache
  command: yum makecache
  args:
    warn: no
