---

- name: Get admin context
  shell: kubectl config view -o=jsonpath='{range .contexts[*]}{.name}{"\n"}{end}}' | grep system
  register: okd_admin_context

- name: set to admin context
  command: kubectl config set current-context {{ okd_admin_context.stdout_lines[0] }}
  when: okd_admin_context is succeeded
